### ISSUE TITLE
Cargo build failure for MacOS version 11.0.1

### ISSUE THREAD

**Issue by milindjoshi7705** [sd2k/newrelic-sys#2]
No info available on internet for this one. Could you check this please sooner ?
Cargo build is failing with error:
   Compiling newrelic-sys v0.2.0
error: failed to run custom build command for `newrelic-sys v0.2.0`

Caused by:
  process didn't exit successfully: `/Users/mjoshi/Pycharm Projects/ebt_platform_router/target/debug/build/newrelic-sys-3207fcf7b3fec8e4/build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-search=native=/Users/mjoshi/Pycharm Projects/ebt_platform_router/target/debug/build/newrelic-sys-026e9598a8f1bd63/out
  cargo:rustc-link-lib=static=newrelic
  cargo:rustc-link-lib=dylib=pcre
  /Library/Developer/CommandLineTools/usr/bin/make -C vendor/newrelic/axiom
  cc -DNR_SYSTEM_DARWIN=1 -DHAVE_BACKTRACE=1 -DHAVE_DEV_FD=1 -DHAVE_PTHREAD_MUTEX_ERRORCHECK=1  -std=gnu99 -fPIC -DPIC -pthread -Wall -Werror -Wextra -Wbad-function-cast -Wcast-qual -Wdeclaration-after-statement -Wformat -Wformat-security -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-prototypes -Wno-write-strings -Wpointer-arith -Wshadow -Wstrict-prototypes -Wswitch-enum -Wbool-conversion -Wempty-body -Wheader-hygiene -Wimplicit-fallthrough -Wlogical-op-parentheses -Wloop-analysis -Wsizeof-array-argument -Wstring-conversion -Wswitch -Wswitch-enum -Wuninitialized -Wunused-label -Wno-typedef-redefinition -Wno-missing-field-initializers -I/usr/local/Cellar/pcre/8.44/include -std=gnu99 -fPIC -DPIC -pthread -Wall -Werror -Wextra -Wbad-function-cast -Wcast-qual -Wdeclaration-after-statement -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-prototypes -Wno-write-strings -Wpointer-arith -Wshadow -Wstrict-prototypes -Wswitch-enum -Wbool-conversion -Wempty-body -Wheader-hygiene -Wimplicit-fallthrough -Wlogical-op-parentheses -Wloop-analysis -Wsizeof-array-argument -Wstring-conversion -Wswitch -Wswitch-enum -Wuninitialized -Wunused-label -Wno-typedef-redefinition -O0 -g3 -DNR_CAGENT -MMD -MP -c util_hash.c -o util_hash.o
  "./vendor/libnewrelic.a"

  --- stderr
  cat: ../../VERSION: No such file or directory
  fatal: not a git repository (or any of the parent directories): .git
  util_hash.c:193:5: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
      case 2:
      ^
  util_hash.c:193:5: note: insert '__attribute__((fallthrough));' to silence this warning
      case 2:
      ^
      __attribute__((fallthrough));
  util_hash.c:193:5: note: insert 'break;' to avoid fall-through
      case 2:
      ^
      break;
  util_hash.c:196:5: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
      case 1:
      ^
  util_hash.c:196:5: note: insert '__attribute__((fallthrough));' to silence this warning
      case 1:
      ^
      __attribute__((fallthrough));
  util_hash.c:196:5: note: insert 'break;' to avoid fall-through
      case 1:
      ^
      break;
  2 errors generated.
  make[1]: *** [util_hash.o] Error 1
  make: *** [vendor/newrelic/axiom/libaxiom.a] Error 2
  thread 'main' panicked at 'Could not copy object files: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/mjoshi/.cargo/registry/src/github.com-1ecc6299db9ec823/newrelic-sys-0.2.0/build.rs:25:61
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by sd2k** [comment]
Hi @milindjoshi7705! Unfortunately the New Relic C-SDK (which this library uses) is [only compatible with Linux](https://github.com/newrelic/c-sdk#requirements) so you'll need to use Docker or a similar alternative if you want to develop with this library on MacOS.

**Comment by milindjoshi7705** [comment]
ok, just want to understand what changes are causing this to fail as it is working on macOs version 10(Mojave). Any pointers will be helpful.

**Comment by sd2k** [comment]
Huh, interesting, I'm surprised it was ever working on MacOS 10. In any case, this is an issue with the compilation of the underlying C SDK - could you check to see that your machine meets the requirements at https://github.com/newrelic/c-sdk#requirements?

**Comment by milindjoshi7705** [comment]
I am able to get this done on ubuntu 20.x with required dependencies. Will try to get it on docker image on Mac. Thanks for response, closing this thread.

**Comment by nil8893** [comment]
any idea how to get this done on mac os 11+ using docker?

**Comment by sd2k** [comment]
It looks like the bindings will need updating using a newer version of bindgen which includes a fix for https://github.com/rust-lang/rust-bindgen/issues/603.

(An alternative would be to create the bindings as part of the build script but that'd include a lot of dependencies and slow down build times considerably)

**Comment by sd2k** [comment]
@nil8893 Ignore my previous comment. This crate (`newrelic-sys`) _should_ already compile in Docker on MacOS 11+ regardless of architecture, provided the target OS is Linux. The `newrelic` crate will fail right now though - hopefully https://github.com/sd2k/newrelic/pull/15 will fix that. Are you able to give it a try and let me know?
